server:
    port: 8084

spring:
    profiles:
        active: prod
    data:
        mongodb:
            host: localhost
            port: 27017
            database: volvo

    mail:
        baseUrl: http://localhost:8090

    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9998
    graphite:
        enabled: false
        host: localhost
        port: 2002
        prefix: volvo


